version: "3"
services:
    web:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: Dockerfile.dev

        image: sayantabonny/burgerbuilder:Test
        ports:
            - "1234:3000"
        volumes:
            - /app/node_modules
            - .:/app